name: Verify Hackathon Submission

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for commit verification
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Run verification script
      run: node verify-submission.js
      continue-on-error: true
      
    - name: Check for timestamp file
      run: |
        if [ -f .hackathon-start ]; then
          echo "✅ Timestamp file found"
          cat .hackathon-start
        else
          echo "⚠️ Timestamp file not found - please create it!"
          exit 0
        fi
    
    - name: Commit count
      run: |
        COMMIT_COUNT=$(git log --oneline --all --grep="acta-hackathon-setup" --invert-grep | wc -l | xargs)
        echo "Participant commits: $COMMIT_COUNT (excluding acta-hackathon-setup)"
        if [ $COMMIT_COUNT -ge 5 ]; then
          echo "✅ Minimum commit count met"
        else
          echo "⚠️ Consider making more commits (current: $COMMIT_COUNT, recommended: 5+)"
        fi

